main: "moe.langua.lab.minecraft.scoop.BootStrap"
version: "${project.version}"
build: "${build.timestamp}"
name: "MelonScoop"
api-version: "1.13"
commands:
  dig:
    usage: /dig <player|ip> <PlayerName|IPAddress>
    permission: melonscoop.dig
